#spring.config.activate.on-profile=${SPRING_PROFILES_ACTIVE:dev}
server.port=${APP_PORT:8082}
spring.application.name=${AUTH_SERVICE_NAME:auth-service}
spring.liquibase.enabled=${SPRING_LIQUIBASE_ENABLED:false}
## ===============================
## Primary Database (Book Database)
## ===============================
#spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
spring.datasource.driver-class-name=org.postgresql.Driver
HOST=${DB_HOST:localhost}
HOST_PORT=${DB_HOST_PORT:5432}
DB_AUTH=${POSTGRES_DB_AUTH:auth_service_db}
#spring.datasource.url=jdbc:postgresql://${HOST}:${HOST_PORT}/${DB_AUTH}
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_service_db
spring.datasource.username=${POSTGRES_USER:admin}
spring.datasource.password=${POSTGRES_PASSWORD:admin}

## ===============================
## JPA Configuration
## ===============================
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM:org.hibernate.dialect.PostgreSQLDialect}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL:true}

spring.docker.compose.enabled=${SPRING_DOCKER_COMPOSE_ENABLED:false}
spring.devtools.restart.enabled=true